### ISSUE TITLE
Проблема периодической отправки показаний

### ISSUE THREAD

**Issue by VaNiK3230** [dentra/ha-pesc#21]
**Суть проблемы**

Падает скрипт при обновлении показаний на сайте ПСК https://ikus.pesc.ru
Падения происходят, если скрипт не вызывался несколько часов и более.
При этом показания на сайте обновляются, но не обновляются сенсоры из интеграции, не приходит уведомление (в моем случае: телеграм).

Повторное выполнения скрипта через 1, 2, 10 минут происходит нормально.

Предположительно, интеграция при "первом" запуске службы update_value не формирует response_variable - вместо словаря тип NoneType

**Ошибка в логе HA**

`2025-01-28 15:48:29.596 ERROR (MainThread) [homeassistant.components.script.sc_dom_electro_prepare_and_send] sc_dom_electro_prepare_and_send: Error executing script. Error for call_service at pos 1: Failed to process the returned action response data, expected a dictionary, but got <class 'NoneType'>`

**Листинг моего скрипта (Основан на примере из описания интеграции):**

```
script:
  sc_dom_electro_prepare_and_send:
    sequence:
      - service: pesc.update_value
        target:
          entity_id:
            - sensor.pesc_00000xxxxx_2
            - sensor.pesc_00000yyyyy_3
        data:
          value:
            - scale_id: 2
              value: >
                {{ states('sensor.vs_neva_mt_114_wi_fi_zzzzzzzz_energy_t1_a_int') }}
            - scale_id: 3
              value: >
                {{ states('sensor.vs_neva_mt_114_wi_fi_zzzzzzzz_energy_t2_a_int') }}
        response_variable: response
        enabled: true
      - condition: template
        value_template: "{{ response.code == 0 }}"
      - service: script.sc_telegram_send
        data:
          message_header: "Показания успешно переданы"
          message_body: |
            Тело сообщения.....
```

**Мои ожидания**

Прошу оказать содействие в решении проблемы. Предполагаю, проблема на стороне интеграции. 
Но возможно где-то я что-то не сделал. 
Ставить костыль в виде повторного запуска скрипта, если первый не прошел, ставить не хочется.
