### ISSUE TITLE
Стоимость отображается в рублях, а по уму надо в RUB/kWh

### ISSUE THREAD

**Issue by sc16me** [dentra/ha-pesc#3]
Стоимость отображается в рублях, а по уму надо в RUB/kWh
Пока подпер костыликом:
```
pesc:

    homeassistant:
      customize:

        sensor.pesc_electricity_day_rub:
          unit_of_measurement: RUB/kWh

        sensor.pesc_electricity_night_rub:
          unit_of_measurement: RUB/kWh

```
Стоимость воды кстати не отображается( Не страшно, но хотелось бы, раз уж оно есть.
![Снимок экрана 2023-10-10 в 17 23 05](https://github.com/dentra/ha-pesc/assets/1618809/05e9ea6c-297b-401d-9937-806daa376d47)

P.S. А так огромное спасибо, очень круто что наконец есть такая интеграция!

**Comment by dentra** [comment]
Так изначально и было, но потом меня что-то смутило )) исправлю

**Comment by sc16me** [comment]
По версии 67121e3:
Заработала отправка показаний, вчера и сегодня утром не работало. Правда смущает то что через приложение на телефоне тоже не оправлялось. Точнее отправлялось, но не обновлялось. Сейчас и там и там с первого раза.
Цены теперь в RUB/kWh. Проблема только в том что вода, тоже стала RUB/kWh) Решил пока тем же костыликом.
Кстати вода стала отображать цены! Ура!)
Еще видел что водотведение ковыряете. По моему скромному мнению, возможно, оно того не стоит. Панель энергия в HA не умеет отображать вывод воды, только ввод. Я например себе водотведение тупо через template сенсор сделал. Цену тоже через template. Показывает и ладно, но вот нужно ли оно в самой интеграции... Если таки будете делать, у меня например два счетчика холодной воды. Водоотведение можно считать по тарифу любого из них (что у меня и сделано).
Еще раз спасибо!

**Comment by dentra** [comment]
о, уже плюс, что по воде появились цены! мне в слепую очень сложно делать изменения, теперь посмотрю в сторону  правильного отображения едениц измерения.

к сожалению, сервис очень часто висит и соответсвенно показания в этот момент отправляться не могут, я специально делал все сенсоры в assumed состоянии иначе в эти моменты они были недоступны.

по водоотведению будет только то что показывает ЛК, самостоятельно считать пока не планировал т.к. действительно это все легко считается шаблонным сенсором. запишу в туду на подумать

**Comment by sc16me** [comment]
У нас общедомовом чатике говорят что они с 9 до (не знаю скольки, 21 может?) работают. Типо в остальное время отключают сайт или базу? от DDoS. Еще говорят через vpn не работает. Короче слухи... 
Тем не менее сайт действительно глючный, как и приложение которое например при поданных показаниях сегодня, говорит что показания переданы 3 дня назад. Кстати нельзя вывести сенсор когда поданы показания? Понятно что из-за всего вышеперечисленного точность будет условная.

P.S. Так для наглядности, _ведь всегда приятно своими глазами увидеть_)
```
pesc:

    homeassistant:
      customize:

        sensor.pesc_hotwater_1014019470500_rub:
          unit_of_measurement: RUB/m³

        sensor.pesc_coldwater_1014019472108_rub:
          unit_of_measurement: RUB/m³

        sensor.pesc_coldwater_1014019491604_rub:
          unit_of_measurement: RUB/m³
```
![Снимок экрана 2023-10-11 в 18 55 00](https://github.com/dentra/ha-pesc/assets/1618809/c58934b1-8164-4f1b-963d-cecd32631168)
