### ISSUE TITLE
Ответ от службы

### ISSUE THREAD

**Issue by Valen13776** [dentra/ha-pesc#9]
Добрый день.
При вызове pesc.update_value, служба возвращает результат работы.
Не могли бы Вы создать пример как можно обработать результаты работы службы?

**Comment by dentra** [comment]
Служба возвращает результат в виде объекта такого вида:
```yaml
code: 0
message: Операция выполнена успешно
payload:
  - scaleId: 2
    value: 16380
  - scaleId: 3
    value: 7672
 ```
Например, вы можете обработать код ошибки (0 - все хорошо) и удостовериться, что ушили именно те данные, которые требовались
